/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import domain.Drzava;
import domain.Gost;
import java.awt.Frame;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import table.models.TableModelGost;
import validation.ValidationException;
import validation.Validator;

/**
 *
 * @author Nikola
 */
public class GostForm extends javax.swing.JDialog {

    private FormMode mode;
    private Gost gost;
    private TableModelGost tableModelGost;
    private boolean nezapamcenGost;

    /**
     * Creates new form GostForm
     */
    public GostForm(java.awt.Frame parent, boolean modal, FormMode mode, Gost gost) throws Exception {
        super(parent, modal);
        initComponents();

        this.mode = mode;
        this.gost = gost;

        prepareForm();

        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        lblIme = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtBroj = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cbDrzava = new javax.swing.JComboBox();
        lblPrezime = new javax.swing.JLabel();
        lblBroj = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblDrzava = new javax.swing.JLabel();
        btn2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGost = new javax.swing.JTable();
        rbGost = new javax.swing.JRadioButton();
        rbDrzava = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btn1.setText("Kreiraj gosta");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        lblIme.setText("Ime:");

        txtIme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtImeMouseClicked(evt);
            }
        });
        txtIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImeActionPerformed(evt);
            }
        });

        txtPrezime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPrezimeMouseClicked(evt);
            }
        });
        txtPrezime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrezimeActionPerformed(evt);
            }
        });

        txtBroj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBrojMouseClicked(evt);
            }
        });

        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });

        cbDrzava.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDrzava.setSelectedIndex(-1);
        cbDrzava.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbDrzavaMouseClicked(evt);
            }
        });
        cbDrzava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDrzavaActionPerformed(evt);
            }
        });

        lblPrezime.setText("Prezime:");

        lblBroj.setText("Broj telefona:");

        lblEmail.setText("Email:");

        lblDrzava.setText("Drzava:");

        btn2.setText("Zapamti gosta");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        tableGost.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableGost);

        rbGost.setText("Pretrazi prema gostu");
        rbGost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGostActionPerformed(evt);
            }
        });

        rbDrzava.setText("Pretrazi prema drzavi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblBroj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDrzava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblIme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(txtBroj, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrezime, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbGost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbDrzava)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDrzava)
                    .addComponent(rbGost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIme)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrezime)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBroj)
                    .addComponent(txtBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDrzava)
                    .addComponent(cbDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1)
                    .addComponent(btn2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        switch (mode) {
            case ADD:
                btn1Add();
                break;
            case SEARCH:
                btn1Search();
                break;
            case VIEW:
                btn1View();
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void cbDrzavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDrzavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDrzavaActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        switch (mode) {
            case ADD:
                btn2Add();
                break;
            case SEARCH:
                btn2Search();
                break;
            case VIEW:
                btn2View();
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void txtImeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtImeMouseClicked
        if (!txtIme.isEditable() && mode == FormMode.VIEW) {
            txtIme.setEditable(true);
        }
    }//GEN-LAST:event_txtImeMouseClicked

    private void cbDrzavaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDrzavaMouseClicked
        if (!cbDrzava.isEnabled() && mode == FormMode.VIEW) {
            cbDrzava.setEnabled(true);
        }
    }//GEN-LAST:event_cbDrzavaMouseClicked

    private void txtPrezimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrezimeMouseClicked
        if (!txtPrezime.isEditable() && mode == FormMode.VIEW) {
            txtPrezime.setEditable(true);
        }
    }//GEN-LAST:event_txtPrezimeMouseClicked

    private void txtBrojMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBrojMouseClicked
        if (!txtBroj.isEditable() && mode == FormMode.VIEW) {
            txtBroj.setEditable(true);
        }
    }//GEN-LAST:event_txtBrojMouseClicked

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        if (!txtEmail.isEditable() && mode == FormMode.VIEW) {
            txtEmail.setEditable(true);
        }
    }//GEN-LAST:event_txtEmailMouseClicked

    private void txtPrezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrezimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrezimeActionPerformed

    private void txtImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImeActionPerformed

    private void rbGostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbGostActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (nezapamcenGost) {
            int confirm = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da zatvorite formu pre nego sto sacuvate gosta? Kreiran gost ce biti obrisan.", "Potvrda zatvaranja", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    Controller.getInstance().obrisiGost(gost);
                } catch (Exception ex) {
                    Logger.getLogger(GostForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                dispose();
            }
        } else {
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JComboBox cbDrzava;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBroj;
    private javax.swing.JLabel lblDrzava;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JRadioButton rbDrzava;
    private javax.swing.JRadioButton rbGost;
    private javax.swing.JTable tableGost;
    private javax.swing.JTextField txtBroj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() throws Exception {
        fillCbDrzava();
        switch (mode) {
            case ADD:
                prepareAdd();
                break;
            case SEARCH:
                prepareSearch();
                break;
            case VIEW:
                prepareView();
                break;
            default:
                throw new AssertionError();
        }
    }

    private void fillCbDrzava() throws Exception {
        cbDrzava.removeAllItems();
        List<Drzava> drzave = Controller.getInstance().vratiListuSvihDrzava();
        for (Drzava drzava : drzave) {
            cbDrzava.addItem(drzava);
        }
    }

    private void prepareAdd() {
        this.setTitle("Kreiranje gosta");
        btn1.setText("Kreiraj gosta");
        btn2.setText("Zapamti gosta");
        rbGost.setVisible(false);
        rbDrzava.setVisible(false);
        jScrollPane1.setVisible(false);
        tableGost.setVisible(false);
        btn2.setEnabled(false);
        txtIme.setEditable(false);
        txtPrezime.setEditable(false);
        txtBroj.setEditable(false);
        txtEmail.setEditable(false);
        cbDrzava.setEnabled(false);
    }

    private void prepareSearch() {
        this.setTitle("Pretraga gosta");
        btn1.setText("Pretrazi po kriteriujumima");
        btn2.setText("Nadji gosta");
        btn2.setEnabled(false);
        jScrollPane1.setVisible(false);
        tableGost.setVisible(false);
        ButtonGroup radioButtons = new ButtonGroup();
        radioButtons.add(rbGost);
        radioButtons.add(rbDrzava);
        rbGost.setSelected(true);
        rbGost.addActionListener(evt -> radioButtonSelected(true));
        rbDrzava.addActionListener(evt -> radioButtonSelected(false));
        radioButtonSelected(true);
    }

    private void prepareView() {
        this.setTitle("Pregled gosta");
        btn1.setText("Zapamti podatke");
        btn2.setText("Obrisi gosta");
        txtIme.setText(gost.getIme());
        txtPrezime.setText(gost.getPrezime());
        txtBroj.setText(gost.getBroj());
        txtEmail.setText(gost.getEmail());
        cbDrzava.setSelectedItem(gost.getDrzava());
        txtIme.setEditable(false);
        txtPrezime.setEditable(false);
        txtBroj.setEditable(false);
        txtEmail.setEditable(false);
        cbDrzava.setEnabled(false);
        jScrollPane1.setVisible(false);
        tableGost.setVisible(false);
        rbGost.setVisible(false);
        rbDrzava.setVisible(false);
    }

    private void btn1Add() {
        try {
            gost = new Gost();
            gost = Controller.getInstance().kreirajGost(gost);
            btn1.setEnabled(false);
            btn2.setEnabled(true);
            txtIme.setEditable(true);
            txtPrezime.setEditable(true);
            txtBroj.setEditable(true);
            txtEmail.setEditable(true);
            cbDrzava.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Sistem je kreirao gosta", "Uspesno kreiranje", JOptionPane.INFORMATION_MESSAGE);
            nezapamcenGost = true;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da kreira gosta", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btn1Search() {
        try {
            List<Gost> gosti;
            if (rbGost.isSelected()) {
                if (!txtBroj.getText().trim().isEmpty()) {
                    Validator.startValidation()
                            .validateStringLength(txtBroj.getText().trim(), "Uneti broj mora imati izmedju 8 i 14 karaktera", 8, 14)
                            .throwIfInvalid();
                }
                if (!txtEmail.getText().trim().isEmpty()) {
                    Validator.startValidation()
                            .validateStringContains(txtEmail.getText().trim(), "Uneti email mora da sadrzi '@'", "@")
                            .throwIfInvalid();
                }
                gost = new Gost();
                gost.setIme(txtIme.getText().trim());
                gost.setPrezime(txtPrezime.getText().trim());
                gost.setBroj(txtBroj.getText().trim());
                gost.setEmail(txtEmail.getText().trim());
                gost.setDrzava((Drzava) cbDrzava.getSelectedItem());
                gosti = Controller.getInstance().vratiListuGost(gost);
            } else {
                Drzava d = new Drzava();
                if (!txtIme.getText().trim().isEmpty()) {
                    Validator.startValidation()
                            .validateStringLength(txtIme.getText().trim(), "Uneti naziv drzave mora imati vise od 2 karaktera", 2, null)
                            .throwIfInvalid();
                }
                if (!txtPrezime.getText().trim().isEmpty()) {
                    Validator.startValidation()
                            .validateStringLength(txtPrezime.getText().trim(), "Uneti skraceni naziv mora imati izmedju 2 i 3 karaktera", 2, 3)
                            .throwIfInvalid();
                }
                if (!txtEmail.getText().trim().isEmpty()) {
                    Validator.startValidation()
                            .validateStringStartsWith(txtEmail.getText().trim(), "Uneti pozivni broj mora poceti sa '+'", "+")
                            .throwIfInvalid();
                }
                d.setNaziv(txtIme.getText().trim());
                d.setSkraceniNaziv(txtPrezime.getText().trim());
                d.setKontinent(txtBroj.getText().trim());
                d.setPozivniBroj(txtEmail.getText().trim());
                gosti = Controller.getInstance().vratiListuGost(d);
            }
            if (gosti.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ne postoji gost koji odgovara unetim kriterijumima", "Nije pronadjen gost", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(this, "Sistem je nasao goste po zadatim kriterijumima", "Uspesno pronadjeni gosti", JOptionPane.INFORMATION_MESSAGE);
            tableModelGost = new TableModelGost(gosti);
            tableGost.setModel(tableModelGost);
            jScrollPane1.setVisible(true);
            tableGost.setVisible(true);
            this.pack();
            btn2.setEnabled(true);

        } catch (ValidationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Pogresno unete vrednosti", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje goste po zadatim kriterijumima", "Greska", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void btn1View() {
        try {
            validateGost();
            gost.setIme(txtIme.getText().trim());
            gost.setPrezime(txtPrezime.getText().trim());
            gost.setBroj(txtBroj.getText().trim());
            gost.setEmail(txtEmail.getText().trim());
            gost.setDrzava((Drzava) cbDrzava.getSelectedItem());
            Controller.getInstance().promeniGost(gost);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio gosta", "Uspesna izmena", JOptionPane.INFORMATION_MESSAGE);
            txtIme.setEditable(false);
            txtPrezime.setEditable(false);
            txtBroj.setEditable(false);
            txtEmail.setEditable(false);
            cbDrzava.setEnabled(false);
        } catch (ValidationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska pri unosu podataka", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti gosta", "Greska", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void btn2Add() {
        try {
            validateGost();
            gost.setIme(txtIme.getText().trim());
            gost.setPrezime(txtPrezime.getText().trim());
            gost.setBroj(txtBroj.getText().trim());
            gost.setEmail(txtEmail.getText().trim());
            gost.setDrzava((Drzava) cbDrzava.getSelectedItem());
            Controller.getInstance().promeniGost(gost);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio gosta", "Uspesno zapamcen gost", JOptionPane.INFORMATION_MESSAGE);
            nezapamcenGost = false;
            GostForm gostForm = new GostForm((Frame) this.getOwner(), true, FormMode.VIEW, gost);
            gostForm.pack();
            this.dispose();
            gostForm.setVisible(true);
        } catch (ValidationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska pri unosu podataka", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti gosta", "Greska", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void validateGost() throws ValidationException {
        Validator.startValidation().validateNotNullOrEmpty(txtIme.getText(), "Morate uneti ime!")
                .validateNotNullOrEmpty(txtPrezime.getText(), "Morate uneti prezime!")
                .validateNotNullOrEmpty(txtBroj.getText(), "Morate uneti broj telefona!")
                .validateStringLength(txtBroj.getText(), "Telefon mora imati izmedju 8 i 14 karaktera!", 8, 14)
                .validateNotNullOrEmpty(txtEmail.getText(), "Morate uneti email!")
                .validateStringContains(txtEmail.getText(), "Email mora sadrzati '@'", "@")
                .validateNotNull(cbDrzava.getSelectedItem(), "Morate izabrati drzavu!")
                .throwIfInvalid();
    }

    private void btn2Search() {
        int row = tableGost.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati gosta iz tabele!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            Gost g = tableModelGost.getGostAt(row);
            g = Controller.getInstance().pretraziGost(g);
            JOptionPane.showMessageDialog(this, "Sistem je nasao gosta", "Uspesno pronadjen gost", JOptionPane.INFORMATION_MESSAGE);
            GostForm gostForm = new GostForm((Frame) this.getOwner(), true, FormMode.VIEW, g);
            gostForm.pack();
            this.dispose();
            gostForm.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje gosta", "Greska", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void btn2View() {
        int confirm = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete gosta?", "Potvrda brisanja", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        try {
            Controller.getInstance().obrisiGost(gost);
            JOptionPane.showMessageDialog(this, "Sistem je obrisao gosta", "Uspesno brisanje", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise gosta", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void radioButtonSelected(boolean poGostu) {
        txtIme.setText("");
        txtPrezime.setText("");
        txtBroj.setText("");
        txtEmail.setText("");
        if (poGostu) {
            cbDrzava.setVisible(true);
            lblDrzava.setVisible(true);
            lblIme.setText("Ime:");
            lblPrezime.setText("Prezime");
            lblBroj.setText("Broj telefona:");
            lblEmail.setText("Email");
            cbDrzava.setSelectedIndex(-1);
        } else {
            lblIme.setText("Naziv:");
            lblPrezime.setText("Skraceni naziv:");
            lblBroj.setText("Kontinent");
            lblEmail.setText("Pozivni broj:");
            cbDrzava.setVisible(false);
            lblDrzava.setVisible(false);
        }
        this.pack();
    }

}
