/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import controller.Controller;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nikola
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.setTitle("Home - " + controller.Controller.getInstance().getUlogovanRecepcioner());
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menubarGlavni = new javax.swing.JMenuBar();
        menuDokumenti = new javax.swing.JMenu();
        menuRezervacija = new javax.swing.JMenu();
        menuitemDodajRezervacija = new javax.swing.JMenuItem();
        menuitemPretraziRezervacija = new javax.swing.JMenuItem();
        menuPrimalac = new javax.swing.JMenu();
        menuGost = new javax.swing.JMenu();
        menuitemDodajGost = new javax.swing.JMenuItem();
        menuitemPretraziGost = new javax.swing.JMenuItem();
        menuSifarnici = new javax.swing.JMenu();
        menuitemStrucnaSprema = new javax.swing.JMenuItem();
        menuKorisnik = new javax.swing.JMenu();
        menuitemLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        menuDokumenti.setText("Dokumenti");

        menuRezervacija.setText("Rezervacija");

        menuitemDodajRezervacija.setText("Dodaj");
        menuitemDodajRezervacija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemDodajRezervacijaActionPerformed(evt);
            }
        });
        menuRezervacija.add(menuitemDodajRezervacija);

        menuitemPretraziRezervacija.setText("Pretrazi");
        menuitemPretraziRezervacija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemPretraziRezervacijaActionPerformed(evt);
            }
        });
        menuRezervacija.add(menuitemPretraziRezervacija);

        menuDokumenti.add(menuRezervacija);

        menubarGlavni.add(menuDokumenti);

        menuPrimalac.setText("Primalac usluge");

        menuGost.setText("Gost");

        menuitemDodajGost.setText("Dodaj");
        menuitemDodajGost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemDodajGostActionPerformed(evt);
            }
        });
        menuGost.add(menuitemDodajGost);

        menuitemPretraziGost.setText("Pretrazi");
        menuitemPretraziGost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemPretraziGostActionPerformed(evt);
            }
        });
        menuGost.add(menuitemPretraziGost);

        menuPrimalac.add(menuGost);

        menubarGlavni.add(menuPrimalac);

        menuSifarnici.setText("Sifarnici");

        menuitemStrucnaSprema.setText("Strucna sprema");
        menuitemStrucnaSprema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemStrucnaSpremaActionPerformed(evt);
            }
        });
        menuSifarnici.add(menuitemStrucnaSprema);

        menubarGlavni.add(menuSifarnici);

        menuKorisnik.setText("Korisnik");

        menuitemLogout.setText("Odjava");
        menuitemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemLogoutActionPerformed(evt);
            }
        });
        menuKorisnik.add(menuitemLogout);

        menubarGlavni.add(menuKorisnik);

        setJMenuBar(menubarGlavni);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuitemDodajGostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemDodajGostActionPerformed
        try {
            GostForm formaGost = new GostForm(this, rootPaneCheckingEnabled, FormMode.ADD, null);
            formaGost.pack();
            formaGost.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuitemDodajGostActionPerformed

    private void menuitemPretraziGostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemPretraziGostActionPerformed
        try {
            GostForm formaGost = new GostForm(this, rootPaneCheckingEnabled, FormMode.SEARCH, null);
            formaGost.pack();
            formaGost.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuitemPretraziGostActionPerformed

    private void menuitemStrucnaSpremaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemStrucnaSpremaActionPerformed
        StrucnaSpremaForm formaS = new StrucnaSpremaForm(this, rootPaneCheckingEnabled);
        formaS.pack();
        formaS.setVisible(true);
    }//GEN-LAST:event_menuitemStrucnaSpremaActionPerformed

    private void menuitemDodajRezervacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemDodajRezervacijaActionPerformed
        try {
            RezervacijaForm formaRezervacija = new RezervacijaForm(this, rootPaneCheckingEnabled, FormMode.ADD, null);
            formaRezervacija.pack();
            formaRezervacija.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuitemDodajRezervacijaActionPerformed

    private void menuitemPretraziRezervacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemPretraziRezervacijaActionPerformed
        try {
            RezervacijaForm formaRezervacija = new RezervacijaForm(this, rootPaneCheckingEnabled, FormMode.SEARCH, null);
            formaRezervacija.pack();
            formaRezervacija.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuitemPretraziRezervacijaActionPerformed

    private void menuitemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemLogoutActionPerformed
        int logoutConfirm = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da se odjavite?", "Logout", JOptionPane.YES_NO_OPTION);
        if (logoutConfirm == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            Controller.getInstance().logout();
            JOptionPane.showMessageDialog(this, "Uspesno odjavljivanje", "Logout", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new LoginForm().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da odjavi korisnika", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuitemLogoutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int confirm = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da zatvorite aplikaciju?", "Potvrda zatvaranja", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Controller.getInstance().logout();
            } catch (Exception ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuDokumenti;
    private javax.swing.JMenu menuGost;
    private javax.swing.JMenu menuKorisnik;
    private javax.swing.JMenu menuPrimalac;
    private javax.swing.JMenu menuRezervacija;
    private javax.swing.JMenu menuSifarnici;
    private javax.swing.JMenuBar menubarGlavni;
    private javax.swing.JMenuItem menuitemDodajGost;
    private javax.swing.JMenuItem menuitemDodajRezervacija;
    private javax.swing.JMenuItem menuitemLogout;
    private javax.swing.JMenuItem menuitemPretraziGost;
    private javax.swing.JMenuItem menuitemPretraziRezervacija;
    private javax.swing.JMenuItem menuitemStrucnaSprema;
    // End of variables declaration//GEN-END:variables
}
