/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import domain.Drzava;
import domain.Gost;
import domain.Recepcioner;
import domain.Rezervacija;
import domain.Soba;
import domain.StavkaRezervacije;
import java.awt.Frame;
import java.text.ParseException;
import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import table.models.TableModelRezervacija;
import table.models.TableModelStavkaRezervacije;
import validation.ValidationException;
import validation.Validator;

/**
 *
 * @author Nikola
 */
public class RezervacijaForm extends javax.swing.JDialog {

    /**
     * Creates new form RezervacijaForm
     */
    private FormMode mode;
    private Rezervacija rezervacija;
    private TableModelStavkaRezervacije tableModelStavkaRezervacije;
    private TableModelRezervacija tableModelRezervacija;
    private boolean nezapamcenaRez;
    private SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");

    public RezervacijaForm(java.awt.Frame parent, boolean modal, FormMode mode, Rezervacija rezervacija) throws Exception {
        super(parent, modal);
        initComponents();

        this.mode = mode;
        this.rezervacija = rezervacija;
        prepareForm();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKreirajRez = new javax.swing.JButton();
        btnZapamtiRez = new javax.swing.JButton();
        cbDrzava = new javax.swing.JComboBox();
        txtExtra = new javax.swing.JTextField();
        cbGost = new javax.swing.JComboBox();
        lblExtra = new javax.swing.JLabel();
        lblGost = new javax.swing.JLabel();
        txtNacinRezervisanja = new javax.swing.JTextField();
        txtNacinPlacanja = new javax.swing.JTextField();
        lblNacin = new javax.swing.JLabel();
        lblNacinRez = new javax.swing.JLabel();
        rbRezervacija = new javax.swing.JRadioButton();
        rbGost = new javax.swing.JRadioButton();
        lblBalkon = new javax.swing.JLabel();
        checkboxBalkon = new javax.swing.JCheckBox();
        cbRecepcioner = new javax.swing.JComboBox();
        lblRecepcioner = new javax.swing.JLabel();
        lblUkupanIznos = new javax.swing.JLabel();
        txtUkupanIznos = new javax.swing.JTextField();
        txtDatum = new javax.swing.JTextField();
        lblDatum = new javax.swing.JLabel();
        rbRecepcioner = new javax.swing.JRadioButton();
        rbSoba = new javax.swing.JRadioButton();
        btnDodajStavku = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        btnIzmeniStavku = new javax.swing.JButton();
        txtDatumIsteka = new javax.swing.JTextField();
        txtIznosPoGostu = new javax.swing.JTextField();
        txtIznos = new javax.swing.JTextField();
        lblDatumIsteka = new javax.swing.JLabel();
        lblIznosPoGostu = new javax.swing.JLabel();
        lblIznos = new javax.swing.JLabel();
        txtDatumPocetka = new javax.swing.JTextField();
        txtBrojDana = new javax.swing.JTextField();
        txtBrojGostiju = new javax.swing.JTextField();
        cbSoba = new javax.swing.JComboBox();
        lblDatumPocetka = new javax.swing.JLabel();
        lblBrojDana = new javax.swing.JLabel();
        lblBrojGostiju = new javax.swing.JLabel();
        lblSoba = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        lblDrzava = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnKreirajRez.setText("Kreiraj rezervaciju");
        btnKreirajRez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajRezActionPerformed(evt);
            }
        });

        btnZapamtiRez.setText("Zapamti rezervaciju ");
        btnZapamtiRez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapamtiRezActionPerformed(evt);
            }
        });

        cbDrzava.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDrzava.setSelectedIndex(-1);
        cbDrzava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDrzavaActionPerformed(evt);
            }
        });

        txtExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExtraActionPerformed(evt);
            }
        });

        cbGost.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbGost.setSelectedIndex(-1);
        cbGost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGostActionPerformed(evt);
            }
        });

        lblExtra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblExtra.setText("jLabel1");

        lblGost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGost.setText("Gost:");

        txtNacinPlacanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacinPlacanjaActionPerformed(evt);
            }
        });

        lblNacin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNacin.setText("Nacin placanja:");

        lblNacinRez.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNacinRez.setText("Nacin rezervisanja:");

        rbRezervacija.setText("Rezervacija");
        rbRezervacija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRezervacijaActionPerformed(evt);
            }
        });

        rbGost.setText("Gost");

        lblBalkon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBalkon.setText("jLabel2");
        lblBalkon.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        checkboxBalkon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxBalkonActionPerformed(evt);
            }
        });

        cbRecepcioner.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbRecepcioner.setSelectedIndex(-1);
        cbRecepcioner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRecepcionerActionPerformed(evt);
            }
        });

        lblRecepcioner.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRecepcioner.setText("Recepcioner:");

        lblUkupanIznos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUkupanIznos.setText("Ukupan iznos(RSD):");

        txtUkupanIznos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUkupanIznosActionPerformed(evt);
            }
        });

        txtDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatumActionPerformed(evt);
            }
        });

        lblDatum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDatum.setText("Datum:");

        rbRecepcioner.setText("Recepcioner");
        rbRecepcioner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRecepcionerActionPerformed(evt);
            }
        });

        rbSoba.setText("Soba");

        btnDodajStavku.setText("Dodaj stavku");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnObrisiStavku.setText("Obrisi stavku");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        btnIzmeniStavku.setText("Izmeni stavku");
        btnIzmeniStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniStavkuActionPerformed(evt);
            }
        });

        txtDatumIsteka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatumIstekaActionPerformed(evt);
            }
        });

        txtIznosPoGostu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIznosPoGostuActionPerformed(evt);
            }
        });

        txtIznos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIznosActionPerformed(evt);
            }
        });

        lblDatumIsteka.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDatumIsteka.setText("Datum isteka:");

        lblIznosPoGostu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIznosPoGostu.setText("Iznos po gostu(RSD):");

        lblIznos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIznos.setText("Iznos(RSD):");

        txtDatumPocetka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatumPocetkaActionPerformed(evt);
            }
        });
        txtDatumPocetka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDatumPocetkaKeyReleased(evt);
            }
        });

        txtBrojDana.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBrojDanaKeyReleased(evt);
            }
        });

        txtBrojGostiju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrojGostijuActionPerformed(evt);
            }
        });
        txtBrojGostiju.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBrojGostijuKeyReleased(evt);
            }
        });

        cbSoba.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbSoba.setSelectedIndex(-1);
        cbSoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSobaActionPerformed(evt);
            }
        });

        lblDatumPocetka.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDatumPocetka.setText("Datum pocetka:");

        lblBrojDana.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBrojDana.setText("Broj dana:");

        lblBrojGostiju.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBrojGostiju.setText("Broj gostiju:");

        lblSoba.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSoba.setText("Soba:");

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStavke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStavkeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStavke);

        lblDrzava.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbRezervacija)
                                        .addGap(65, 65, 65)
                                        .addComponent(rbGost))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNacinRez, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNacinRezervisanja, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblGost, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbGost, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDrzava)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNacin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNacinPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(138, 138, 138)
                                            .addComponent(rbRecepcioner)
                                            .addGap(56, 56, 56)
                                            .addComponent(rbSoba))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblDatumIsteka, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtDatumIsteka, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblIznosPoGostu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtIznosPoGostu, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRecepcioner, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbRecepcioner, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBalkon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(checkboxBalkon, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblDatumPocetka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblBrojDana, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(lblBrojGostiju, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblSoba, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbSoba, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBrojDana, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBrojGostiju, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnKreirajRez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnZapamtiRez, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(btnDodajStavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnObrisiStavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIzmeniStavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbGost)
                                    .addComponent(rbRezervacija))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNacinPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNacin))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNacinRezervisanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNacinRez)
                                        .addComponent(lblUkupanIznos)
                                        .addComponent(btnZapamtiRez)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbGost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGost)
                                    .addComponent(cbRecepcioner, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRecepcioner)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbRecepcioner)
                                    .addComponent(rbSoba))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDatum)
                                    .addComponent(btnKreirajRez))))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBalkon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblExtra))))
                    .addComponent(checkboxBalkon, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrzava))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatumPocetka)
                    .addComponent(lblDatumIsteka)
                    .addComponent(txtDatumIsteka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodajStavku))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrojDana)
                    .addComponent(txtBrojDana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIznosPoGostu)
                    .addComponent(txtIznosPoGostu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObrisiStavku))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrojGostiju)
                    .addComponent(txtBrojGostiju, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIznos)
                    .addComponent(txtIznos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzmeniStavku))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoba)
                    .addComponent(cbSoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajRezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajRezActionPerformed
        switch (mode) {
            case ADD:
                btn1Add();
                break;
            case SEARCH:
                btn1Search();
                break;
            case VIEW:
                btn1View();
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_btnKreirajRezActionPerformed

    private void txtIznosPoGostuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIznosPoGostuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIznosPoGostuActionPerformed

    private void txtDatumPocetkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatumPocetkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatumPocetkaActionPerformed

    private void btnZapamtiRezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapamtiRezActionPerformed
        switch (mode) {
            case ADD:
                btn2Add();
                break;
            case SEARCH:
                btn2Search();
                break;
            case VIEW:
               // btn2View();
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_btnZapamtiRezActionPerformed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        try {
            validateStavkaRezervacije();
            StavkaRezervacije sr = new StavkaRezervacije();
            sr.setBrojDana(Integer.parseInt(txtBrojDana.getText().trim()));
            sr.setBrojGostiju(Integer.parseInt(txtBrojGostiju.getText().trim()));
            sr.setDatumPocetka(dateFormat.parse(txtDatumPocetka.getText().trim()));
            sr.setDatumIsteka(dateFormat.parse(txtDatumIsteka.getText().trim()));
            sr.setSoba((Soba) cbSoba.getSelectedItem());
            sr.setIznos(Double.parseDouble(txtIznos.getText().trim()));
            sr.setIznosPoGostu(Double.parseDouble(txtIznosPoGostu.getText().trim()));
            sr.setRezervacija(rezervacija);
            tableModelStavkaRezervacije.addStavkaRezervacije(sr);
            txtUkupanIznos.setText(String.format("%.2f", tableModelStavkaRezervacije.getUkupanIznos()));
            btnObrisiStavku.setEnabled(true);
            btnIzmeniStavku.setEnabled(true);
            txtDatumPocetka.setText("");
            txtDatumIsteka.setText("");
            txtBrojDana.setText("");
            txtBrojGostiju.setText("");
            txtIznosPoGostu.setText("");
            txtIznos.setText("");
            cbSoba.setSelectedIndex(-1);
        } catch (ValidationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska pri unosu podataka", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(RezervacijaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void txtDatumPocetkaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatumPocetkaKeyReleased
        if (txtBrojDana != null && !(txtBrojDana.getText().trim().isEmpty())) {
            if (checkDatePattern(txtDatumPocetka.getText().trim())) {
                setDatumIsteka();
            }
        }
    }//GEN-LAST:event_txtDatumPocetkaKeyReleased

    private void txtBrojDanaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrojDanaKeyReleased
        if (checkDatePattern(txtDatumPocetka.getText().trim()) && txtBrojDana != null && !(txtBrojDana.getText().trim().isEmpty())) {
            setDatumIsteka();
        }
        if (cbSoba.getSelectedItem() != null && txtBrojDana != null && !(txtBrojDana.getText().trim().isEmpty())) {
            setIznos();
        }
        if (txtBrojDana == null || txtBrojDana.getText().trim().isEmpty()) {
            txtDatumIsteka.setText("");
            txtIznos.setText("");
            txtIznosPoGostu.setText("");
        }
    }//GEN-LAST:event_txtBrojDanaKeyReleased

    private void txtBrojGostijuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrojGostijuKeyReleased
        if (txtIznos != null && !(txtIznos.getText().trim().isEmpty()) && txtBrojDana != null && !(txtBrojGostiju.getText().trim().isEmpty())) {
            int brojGostiju = Integer.parseInt(txtBrojGostiju.getText().trim());
            if (brojGostiju <= 0) {
                txtIznosPoGostu.setText("Greska");
                return;
            }
            double iznos = Double.parseDouble(txtIznos.getText().trim());
            double iznosPoGostu = iznos / brojGostiju;
            txtIznosPoGostu.setText(String.format("%.2f", iznosPoGostu));
        }
        if (txtBrojGostiju.getText().trim().isEmpty()) {
            txtIznosPoGostu.setText("");
        }
    }//GEN-LAST:event_txtBrojGostijuKeyReleased

    private void cbSobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSobaActionPerformed
        if (txtBrojDana != null && !(txtBrojDana.getText().trim().isEmpty())) {
            if (cbSoba.getSelectedItem() != null) {
                setIznos();
            }
        }
    }//GEN-LAST:event_cbSobaActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed
        tableModelStavkaRezervacije.removeStavkaRezervacije(tblStavke.getSelectedRow());
        txtUkupanIznos.setText(String.format("%.2f", tableModelStavkaRezervacije.getUkupanIznos()));
        txtDatumPocetka.setText("");
        txtDatumIsteka.setText("");
        txtBrojDana.setText("");
        txtBrojGostiju.setText("");
        txtIznosPoGostu.setText("");
        txtIznos.setText("");
        cbSoba.setSelectedIndex(-1);
        tblStavke.clearSelection();
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void btnIzmeniStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniStavkuActionPerformed
        if (tblStavke.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Morate odabrati stavku iz tabele", "Greska", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            validateStavkaRezervacije();
            StavkaRezervacije sr = tableModelStavkaRezervacije.getStavkaRezervacijeAt(tblStavke.getSelectedRow());
            sr.setBrojDana(Integer.parseInt(txtBrojDana.getText().trim()));
            sr.setBrojGostiju(Integer.parseInt(txtBrojGostiju.getText().trim()));
            sr.setDatumPocetka(dateFormat.parse(txtDatumPocetka.getText().trim()));
            sr.setDatumIsteka(dateFormat.parse(txtDatumIsteka.getText().trim()));
            sr.setIznosPoGostu(Double.parseDouble(txtIznosPoGostu.getText().trim()));
            sr.setIznos(Double.parseDouble(txtIznos.getText().trim()));
            sr.setSoba((Soba) cbSoba.getSelectedItem());
            tableModelStavkaRezervacije.updateStavkaRezervacije(tblStavke.getSelectedRow(), sr);
            txtUkupanIznos.setText(String.format("%.2f", tableModelStavkaRezervacije.getUkupanIznos()));

            txtDatumPocetka.setText("");
            txtDatumIsteka.setText("");
            txtBrojDana.setText("");
            txtBrojGostiju.setText("");
            txtIznosPoGostu.setText("");
            txtIznos.setText("");
            cbSoba.setSelectedIndex(-1);
            tblStavke.clearSelection();
        } catch (ValidationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska pri unosu podataka", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(RezervacijaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIzmeniStavkuActionPerformed

    private void tblStavkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStavkeMouseClicked
        if (tblStavke.getModel() == tableModelStavkaRezervacije) {
            int row = tblStavke.getSelectedRow();
            if (row == -1) {
                return;
            }
            StavkaRezervacije sr = tableModelStavkaRezervacije.getStavkaRezervacijeAt(row);
            txtDatumPocetka.setText(dateFormat.format(sr.getDatumPocetka()));
            txtDatumIsteka.setText(dateFormat.format(sr.getDatumIsteka()));
            txtBrojDana.setText(String.valueOf(sr.getBrojDana()));
            txtBrojGostiju.setText(String.valueOf(sr.getBrojGostiju()));
            txtIznosPoGostu.setText(String.format(".2f", sr.getIznosPoGostu()));
            txtIznos.setText(String.format(".2f", sr.getIznos()));
            cbSoba.setSelectedItem(sr.getSoba());
        }
    }//GEN-LAST:event_tblStavkeMouseClicked

    private void cbRecepcionerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRecepcionerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRecepcionerActionPerformed

    private void txtIznosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIznosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIznosActionPerformed

    private void txtDatumIstekaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatumIstekaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatumIstekaActionPerformed

    private void txtBrojGostijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrojGostijuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrojGostijuActionPerformed

    private void txtNacinPlacanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacinPlacanjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacinPlacanjaActionPerformed

    private void checkboxBalkonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxBalkonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxBalkonActionPerformed

    private void rbRezervacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRezervacijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRezervacijaActionPerformed

    private void txtExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExtraActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (nezapamcenaRez) {
            int confirm = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da zatvorite formu pre nego sto sacuvate rezervaciju? Kreirana rezervacija ce biti obrisana.", "Potvrda zatvaranja", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    Controller.getInstance().obrisiRezervacija(rezervacija);
                } catch (Exception ex) {
                    Logger.getLogger(RezervacijaForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                dispose();
            }
        } else {
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void cbGostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGostActionPerformed

    private void rbRecepcionerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRecepcionerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRecepcionerActionPerformed

    private void txtDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatumActionPerformed

    private void cbDrzavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDrzavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDrzavaActionPerformed

    private void txtUkupanIznosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUkupanIznosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUkupanIznosActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnIzmeniStavku;
    private javax.swing.JButton btnKreirajRez;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnZapamtiRez;
    private javax.swing.JComboBox cbDrzava;
    private javax.swing.JComboBox cbGost;
    private javax.swing.JComboBox cbRecepcioner;
    private javax.swing.JComboBox cbSoba;
    private javax.swing.JCheckBox checkboxBalkon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBalkon;
    private javax.swing.JLabel lblBrojDana;
    private javax.swing.JLabel lblBrojGostiju;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblDatumIsteka;
    private javax.swing.JLabel lblDatumPocetka;
    private javax.swing.JLabel lblDrzava;
    private javax.swing.JLabel lblExtra;
    private javax.swing.JLabel lblGost;
    private javax.swing.JLabel lblIznos;
    private javax.swing.JLabel lblIznosPoGostu;
    private javax.swing.JLabel lblNacin;
    private javax.swing.JLabel lblNacinRez;
    private javax.swing.JLabel lblRecepcioner;
    private javax.swing.JLabel lblSoba;
    private javax.swing.JLabel lblUkupanIznos;
    private javax.swing.JRadioButton rbGost;
    private javax.swing.JRadioButton rbRecepcioner;
    private javax.swing.JRadioButton rbRezervacija;
    private javax.swing.JRadioButton rbSoba;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtBrojDana;
    private javax.swing.JTextField txtBrojGostiju;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtDatumIsteka;
    private javax.swing.JTextField txtDatumPocetka;
    private javax.swing.JTextField txtExtra;
    private javax.swing.JTextField txtIznos;
    private javax.swing.JTextField txtIznosPoGostu;
    private javax.swing.JTextField txtNacinPlacanja;
    private javax.swing.JTextField txtNacinRezervisanja;
    private javax.swing.JTextField txtUkupanIznos;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() throws Exception {
        fillCbRecepcioner();
        fillCbGost();
        fillCbSoba();
        switch (mode) {
            case ADD:
                prepareAdd();
                break;
            case SEARCH:
                prepareSearch();
                fillCbDrzava();
                break;
            case VIEW:
                prepareView();
                break;
            default:
                throw new AssertionError();
        }
    }

    private void fillCbRecepcioner() throws Exception {
        cbRecepcioner.removeAllItems();
        List<Recepcioner> recepcioneri = Controller.getInstance().vratiListuSvihRecepcionera();
        for (Recepcioner recepcioner : recepcioneri) {
            cbRecepcioner.addItem(recepcioner);
        }
        cbRecepcioner.setSelectedIndex(-1);
    }

    private void fillCbGost() throws Exception {
        cbGost.removeAllItems();
        List<Gost> gosti = Controller.getInstance().vratiListuSvihGostiju();
        for (Gost gost : gosti) {
            cbGost.addItem(gost);
        }
        cbGost.setSelectedIndex(-1);
    }

    private void fillCbSoba() throws Exception {
        cbSoba.removeAllItems();
        List<Soba> sobe = Controller.getInstance().vratiListuSvihSoba();
        for (Soba soba : sobe) {
            cbSoba.addItem(soba);
        }
        cbSoba.setSelectedIndex(-1);
    }

    private void prepareAdd() {
        this.setTitle("Kreiranje rezervacije");
        rbGost.setVisible(false);
        rbRecepcioner.setVisible(false);
        rbRezervacija.setVisible(false);
        rbSoba.setVisible(false);
        lblExtra.setVisible(false);
        lblBalkon.setVisible(false);
        txtExtra.setVisible(false);
        lblDrzava.setVisible(false);
        checkboxBalkon.setVisible(false);
        btnKreirajRez.setText("Kreiraj rezervaciju");
        btnZapamtiRez.setText("Zapamti rezervaciju");
        btnZapamtiRez.setEnabled(false);
        txtNacinPlacanja.setEditable(false);
        txtNacinRezervisanja.setEditable(false);
        cbRecepcioner.setEnabled(false);
        cbGost.setEnabled(false);
        txtDatum.setEditable(false);
        txtUkupanIznos.setEditable(false);
        txtBrojDana.setEditable(false);
        txtBrojGostiju.setEditable(false);
        txtDatumPocetka.setEditable(false);
        txtDatumIsteka.setEditable(false);
        cbSoba.setEnabled(false);
        txtIznosPoGostu.setEditable(false);
        txtIznos.setEditable(false);
        btnDodajStavku.setText("Dodaj stavku");
        btnDodajStavku.setEnabled(false);
        btnObrisiStavku.setText("Obrisi stavku");
        btnObrisiStavku.setEnabled(false);
        btnIzmeniStavku.setText("Izmeni stavku");
        btnIzmeniStavku.setEnabled(false);
        cbDrzava.setVisible(false);
        tableModelStavkaRezervacije = new TableModelStavkaRezervacije(null);
        tblStavke.setModel(tableModelStavkaRezervacije);
    }

    private void prepareSearch() {
        this.setTitle("Pretraga rezervacije");
        btnKreirajRez.setText("Pretrazi po kriterijumima");
        btnZapamtiRez.setText("Nadji rezervaciju");
        jScrollPane1.setVisible(false);
        tblStavke.setVisible(false);
        lblExtra.setVisible(false);
        txtExtra.setVisible(false);
        lblBalkon.setVisible(false);
        lblDrzava.setVisible(false);
        checkboxBalkon.setVisible(false);
        ButtonGroup radioButtons = new ButtonGroup();
        radioButtons.add(rbGost);
        radioButtons.add(rbSoba);
        radioButtons.add(rbRecepcioner);
        radioButtons.add(rbRezervacija);
        rbRezervacija.setSelected(true);
        lblBrojDana.setVisible(false);
        lblBrojGostiju.setVisible(false);
        lblDatumIsteka.setVisible(false);
        lblDatumPocetka.setVisible(false);
        lblIznos.setVisible(false);
        lblIznosPoGostu.setVisible(false);
        lblSoba.setVisible(false);
        cbSoba.setVisible(false);
        txtBrojDana.setVisible(false);
        txtBrojGostiju.setVisible(false);
        txtDatumIsteka.setVisible(false);
        txtDatumPocetka.setVisible(false);
        txtIznos.setVisible(false);
        txtIznosPoGostu.setVisible(false);
        btnDodajStavku.setVisible(false);
        btnIzmeniStavku.setVisible(false);
        btnObrisiStavku.setVisible(false);
        cbDrzava.setVisible(false);

        rbRezervacija.addActionListener(evt -> radioButtonSelected());
        rbRecepcioner.addActionListener(evt -> radioButtonSelected());
        rbSoba.addActionListener(evt -> radioButtonSelected());
        rbGost.addActionListener(evt -> radioButtonSelected());

    }

    private void prepareView() {
        this.setTitle("Pregled rezervacije");
        rbGost.setVisible(false);
        rbRezervacija.setVisible(false);
        rbRecepcioner.setVisible(false);
        rbSoba.setVisible(false);
        lblExtra.setVisible(false);
        txtExtra.setVisible(false);
        lblBalkon.setVisible(false);
        lblDrzava.setVisible(false);
        checkboxBalkon.setVisible(false);
        btnKreirajRez.setText("Zapamti rezervaciju");
        //btnZapamtiRez.setText("Obrisi rezervaciju");
        btnZapamtiRez.setVisible(false);
        txtNacinPlacanja.setText(rezervacija.getNacinPlacanja());
        txtNacinRezervisanja.setText(rezervacija.getNacinRezervisanja());
        txtDatum.setText(dateFormat.format(rezervacija.getDatum()));
        cbGost.setSelectedItem(rezervacija.getGost());
        cbRecepcioner.setSelectedItem(rezervacija.getRecepcioner());
        txtUkupanIznos.setText(String.format("%.2f", rezervacija.getUkupanIznos()));
        tableModelStavkaRezervacije = new TableModelStavkaRezervacije(rezervacija.getStavke());
        tblStavke.setModel(tableModelStavkaRezervacije);
        txtDatum.setEditable(false);
        cbRecepcioner.setEnabled(false);
        txtUkupanIznos.setEnabled(false);
        btnDodajStavku.setText("Dodaj stavku");
        btnObrisiStavku.setText("Obrisi stavku");
        btnIzmeniStavku.setText("Izmeni stavku");
        txtDatumIsteka.setEditable(false);
        txtIznosPoGostu.setEditable(false);
        txtIznos.setEditable(false);
        cbDrzava.setVisible(false);
    }

    private void btn1Add() {
        try {
            Rezervacija r = new Rezervacija();
            r.setRecepcioner(Controller.getInstance().getUlogovanRecepcioner());
            rezervacija = Controller.getInstance().kreirajRezervacija(r);
            cbRecepcioner.setSelectedItem(rezervacija.getRecepcioner());
            txtDatum.setText(dateFormat.format(rezervacija.getDatum()));
            txtNacinPlacanja.setEditable(true);
            txtNacinRezervisanja.setEditable(true);
            cbGost.setEnabled(true);
            txtBrojDana.setEditable(true);
            txtBrojGostiju.setEditable(true);
            txtDatumPocetka.setEditable(true);
            cbSoba.setEnabled(true);
            btnKreirajRez.setEnabled(false);
            btnZapamtiRez.setEnabled(true);
            btnDodajStavku.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Sistem je kreirao rezervaciju", "Uspesno kreiranje rezervacije", JOptionPane.INFORMATION_MESSAGE);
            nezapamcenaRez = true;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da kreira rezervaciju", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btn1Search() {
        try {
            List<Rezervacija> rezervacije;
            rezervacija = new Rezervacija();
            if (rbRezervacija.isSelected()) {
                if (!txtUkupanIznos.getText().trim().isEmpty()) {
                    Validator.startValidation()
                            .validateDoubleGreaterThan(txtUkupanIznos.getText().trim(), "Uneti ukupan iznos mora biti veci od 0", 0.1)
                            .throwIfInvalid();
                    rezervacija.setUkupanIznos(Double.parseDouble(txtUkupanIznos.getText().trim()));
                }
                if (!txtDatum.getText().trim().isEmpty()) {
                    Validator.startValidation()
                            .validateDateFormat(txtDatum.getText().trim(), "Uneti datum mora biti u formatu 'dd.MM.yyyy'", "dd.MM.yyyy")
                            .throwIfInvalid();
                    rezervacija.setDatum(dateFormat.parse(txtDatum.getText().trim()));
                }
                rezervacija.setNacinPlacanja(txtNacinPlacanja.getText().trim());
                rezervacija.setNacinRezervisanja(txtNacinRezervisanja.getText().trim());
                rezervacija.setRecepcioner((Recepcioner) cbRecepcioner.getSelectedItem());
                rezervacija.setGost((Gost) cbGost.getSelectedItem());
                rezervacije = Controller.getInstance().vratiListuRezervacija(rezervacija);
                tableModelRezervacija = new TableModelRezervacija(rezervacije);
            } else if (rbGost.isSelected()) {
                if (!txtNacinRezervisanja.getText().trim().isEmpty()) {
                    Validator.startValidation()
                            .validateStringLength(txtNacinRezervisanja.getText().trim(), "Uneti broj gosta mora imati izmedju 8 i 14 karaktera", 8, 14)
                            .throwIfInvalid();
                }
                if (!txtUkupanIznos.getText().trim().isEmpty()) {
                    Validator.startValidation()
                            .validateStringContains(txtUkupanIznos.getText().trim(), "Uneti email gosta mora da sadrzi '@'", "@")
                            .throwIfInvalid();
                }
                if (cbDrzava.getSelectedIndex() != -1) {
                    Validator.startValidation()
                            .validateNotNull(cbDrzava.getSelectedItem(), "Morate izabrati drzavu")
                            .throwIfInvalid();
                }
                Gost gost = new Gost();
                gost.setIme(txtNacinPlacanja.getText().trim());
                gost.setPrezime(txtDatum.getText().trim());
                gost.setBroj(txtNacinRezervisanja.getText().trim());
                gost.setEmail(txtUkupanIznos.getText().trim());
                gost.setDrzava((Drzava) cbDrzava.getSelectedItem());
                rezervacije = Controller.getInstance().vratiListuRezervacija(gost);
                tableModelRezervacija = new TableModelRezervacija(rezervacije);
            } else if (rbRecepcioner.isSelected()) {
                if (!txtNacinRezervisanja.getText().trim().isEmpty()) {
                    Validator.startValidation()
                            .validateStringLength(txtNacinRezervisanja.getText().trim(), "Uneti broj recepcionera mora imati izmedju 8 i 14 karaktera", 8, 14)
                            .throwIfInvalid();
                }
                if (!txtUkupanIznos.getText().trim().isEmpty()) {
                    Validator.startValidation()
                            .validateStringContains(txtUkupanIznos.getText().trim(), "Uneti email recepcionera mora da sadrzi '@'", "@")
                            .throwIfInvalid();
                }
                Recepcioner r = new Recepcioner();
                r.setIme(txtNacinPlacanja.getText().trim());
                r.setPrezime(txtDatum.getText().trim());
                r.setBroj(txtNacinRezervisanja.getText().trim());
                r.setEmail(txtUkupanIznos.getText().trim());
                r.setKorisnickoIme(txtExtra.getText().trim());
                rezervacije = Controller.getInstance().vratiListuRezervacija(r);
                tableModelRezervacija = new TableModelRezervacija(rezervacije);
            } else {
                if (!txtNacinPlacanja.getText().trim().isEmpty()) {
                    Validator.startValidation()
                            .validateStringLength(txtNacinPlacanja.getText().trim(), "Uneti broj sobe mora imati bar 1 karakter", 1, null)
                            .throwIfInvalid();
                }
                if (!txtDatum.getText().trim().isEmpty()) {
                    Validator.startValidation()
                            .validateIntGreaterThan(txtDatum.getText().trim(), "Uneti broj kreveta mora biti veci od 0", 1)
                            .validateIntLowerThan(txtDatum.getText().trim(), "Uneti broj kreveta mora biti manji od 10", 9)
                            .throwIfInvalid();
                }
                if (!txtNacinRezervisanja.getText().trim().isEmpty()) {
                    Validator.startValidation()
                            .validateIntGreaterThan(txtNacinRezervisanja.getText().trim(), "Uneti sprat sobe mora biti veci ili jednak od 0", 0)
                            .throwIfInvalid();
                }
                if (!txtUkupanIznos.getText().trim().isEmpty()) {
                    Validator.startValidation()
                            .validateDoubleGreaterThan(txtUkupanIznos.getText().trim(), "Uneta cena po danu mora biti veca od 0", 0.1)
                            .throwIfInvalid();
                }
                Soba s = new Soba();
                s.setBroj(txtNacinPlacanja.getText().trim());
                if (!txtDatum.getText().trim().isEmpty()) {
                    s.setBrojKreveta(Integer.parseInt(txtDatum.getText().trim()));
                }
                if (!txtNacinRezervisanja.getText().trim().isEmpty()) {
                    s.setSprat(Integer.parseInt(txtNacinRezervisanja.getText().trim()));
                }else{
                    s.setSprat(-1);
                }
                s.setBalkon(checkboxBalkon.isSelected());
                if (!txtUkupanIznos.getText().trim().isEmpty()) {
                    s.setCenaPoDanu(Double.parseDouble(txtUkupanIznos.getText().trim()));
                }
                rezervacije = Controller.getInstance().vratiListuRezervacija(s);
                tableModelRezervacija = new TableModelRezervacija(rezervacije);
            }
            if (rezervacije.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ne postoji rezervacija koja odgovara unetim kriterijumima", "Nema pronadjenih rezervacija", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(this, "Sistem je nasao rezervacije po zadatim kriterijumima", "Uspesno pronadjene rezervacije", JOptionPane.INFORMATION_MESSAGE);
            tblStavke.setModel(tableModelRezervacija);
            jScrollPane1.setVisible(true);
            tblStavke.setVisible(true);
            this.pack();
            btnZapamtiRez.setEnabled(true);

        } catch (ValidationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Pogresno unete vrednosti", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje rezervacije po zadatim kriterijumima", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btn1View() {
        try {
            validateRezervacija();
            rezervacija.setNacinPlacanja(txtNacinPlacanja.getText().trim());
            rezervacija.setNacinRezervisanja(txtNacinRezervisanja.getText().trim());
            rezervacija.setGost((Gost) cbGost.getSelectedItem());
            rezervacija.setUkupanIznos(Double.parseDouble(txtUkupanIznos.getText().trim()));
            rezervacija.setStavke(tableModelStavkaRezervacije.getStavkeRezervacije());
            Controller.getInstance().promeniRezervacija(rezervacija);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio rezervaciju", "Uspesno zapamcena rezervacija", JOptionPane.INFORMATION_MESSAGE);
            RezervacijaForm rezervacijaForm = new RezervacijaForm((Frame) this.getOwner(), true, FormMode.VIEW, Controller.getInstance().vratiRezervaciju(rezervacija));
            this.dispose();
            rezervacijaForm.setVisible(true);
        } catch (ValidationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska pri unosu podataka", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti rezervaciju", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btn2Add() {
        try {
            validateRezervacija();
            rezervacija.setNacinPlacanja(txtNacinPlacanja.getText().trim());
            rezervacija.setNacinRezervisanja(txtNacinRezervisanja.getText().trim());
            rezervacija.setGost((Gost) cbGost.getSelectedItem());
            rezervacija.setUkupanIznos(Double.parseDouble(txtUkupanIznos.getText().trim()));
            rezervacija.setStavke(tableModelStavkaRezervacije.getStavkeRezervacije());
            Controller.getInstance().promeniRezervacija(rezervacija);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio rezervaciju", "Uspesno zapamcena rezervacija", JOptionPane.INFORMATION_MESSAGE);
            RezervacijaForm rezervacijaForm = new RezervacijaForm((Frame) this.getOwner(), true, FormMode.VIEW, Controller.getInstance().vratiRezervaciju(rezervacija));
            nezapamcenaRez = false;
            this.dispose();
            rezervacijaForm.setVisible(true);
        } catch (ValidationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska pri unosu podataka", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti rezervaciju", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btn2Search() {
        int row = tblStavke.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Morate izabrati rezervaciju iz tabele!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            Rezervacija r = tableModelRezervacija.getRezervacijaAt(row);
            r = Controller.getInstance().vratiRezervaciju(r);
            JOptionPane.showMessageDialog(this, "Sistem je nasao rezervaciju", "Uspesno pronadjena rezervacija", JOptionPane.INFORMATION_MESSAGE);
            RezervacijaForm rezervacijaForm = new RezervacijaForm((Frame) this.getOwner(), true, FormMode.VIEW, r);
            rezervacijaForm.pack();
            this.dispose();
            rezervacijaForm.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje rezervaciju", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }
/*
    private void btn2View() {
        int confirm = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete rezervaciju?", "Potvrda brisanja", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        try {
            Controller.getInstance().obrisiRezervacija(rezervacija);
            JOptionPane.showMessageDialog(this, "Sistem je obrisao rezervaciju", "Uspesno brisanje", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise rezervaciju", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }
*/
    private void setDatumIsteka() {
        try {
            Date datumPocetka = dateFormat.parse(txtDatumPocetka.getText().trim());
            int brojDana = Integer.parseInt(txtBrojDana.getText().trim());
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(datumPocetka);
            calendar.add(Calendar.DATE, brojDana);
            txtDatumIsteka.setText(dateFormat.format(calendar.getTime()));
        } catch (ParseException ex) {
            txtDatumIsteka.setText("Greska");
        }

    }

    private boolean checkDatePattern(String value) {
        dateFormat.setLenient(false);
        try {
            dateFormat.parse(value.trim());
        } catch (ParseException ex) {
            return false;
        }
        return true;

    }

    private void setIznos() {
        Soba soba = (Soba) cbSoba.getSelectedItem();
        int brojDana = Integer.parseInt(txtBrojDana.getText().trim());
        if (brojDana <= 0) {
            txtIznosPoGostu.setText("Greska");
            txtIznos.setText("Greska");
            return;
        }
        Double iznos = brojDana * soba.getCenaPoDanu();
        txtIznos.setText(String.format("%.2f", iznos));
        if (txtBrojGostiju != null && !(txtBrojGostiju.getText().trim().isEmpty())) {
            int brojGostiju = Integer.parseInt(txtBrojGostiju.getText().trim());
            if (brojGostiju <= 0) {
                txtIznosPoGostu.setText("Greska");
                return;
            }
            double iznosPoGostu = iznos / brojGostiju;
            txtIznosPoGostu.setText(String.format("%.2f", iznosPoGostu));
        }
    }

    private void validateStavkaRezervacije() throws ValidationException {
        Validator.startValidation()
                .validateNotNullOrEmpty(txtDatumPocetka.getText(), "Morate uneti datum pocetka")
                .validateDateFormat(txtDatumPocetka.getText(), "Uneti datum mora biti u formatu 'dd.MM.yyyy'", "dd.MM.yyyy")
                .validateBeforeToday(txtDatumPocetka.getText(), "Uneti datum ne sme biti pre danasnjeg datuma")
                .validateNotNullOrEmpty(txtBrojDana.getText(), "Morate uneti broj dana")
                .validateIntGreaterThan(txtBrojDana.getText(), "Broj dana mora biti broj veci od 0", 1)
                .validateNotNullOrEmpty(txtBrojGostiju.getText(), "Morate uneti broj gostiju")
                .validateIntGreaterThan(txtBrojGostiju.getText(), "Broj gostiju mora biti broj veci od 0", 1)
                .validateNotNull(cbSoba.getSelectedItem(), "Morate odabrati sobu")
                .throwIfInvalid();
    }

    private void validateRezervacija() throws ValidationException {
        Validator.startValidation()
                .validateNotNullOrEmpty(txtNacinPlacanja.getText(), "Morate uneti nacin placanja")
                .validateNotNullOrEmpty(txtNacinRezervisanja.getText(), "Morate uneti nacin rezervisanja")
                .validateNotNull(cbGost.getSelectedItem(), "Morate izabrati gosta")
                .validateListNotEmpty(tableModelStavkaRezervacije.getStavkeRezervacije(), "Morate imati bar jednu stavku rezervacije")
                .throwIfInvalid();
    }

    private void radioButtonSelected() {
        txtNacinPlacanja.setText("");
        txtNacinRezervisanja.setText("");
        cbGost.setSelectedIndex(-1);
        cbRecepcioner.setSelectedIndex(-1);
        txtDatum.setText("");
        txtUkupanIznos.setText("");
        txtExtra.setText("");
        checkboxBalkon.setSelected(false);
        if (rbRezervacija.isSelected()) {
            lblNacin.setText("Nacin placanja:");
            lblNacinRez.setText("Nacin rezervisanja:");
            lblGost.setText("Gost:");
            lblDatum.setText("Datum:");
            lblUkupanIznos.setText("Ukupan iznos(RSD):");
            lblRecepcioner.setText("Recepcioner:");
            lblExtra.setVisible(false);
            txtExtra.setVisible(false);
            lblBalkon.setVisible(false);
            checkboxBalkon.setVisible(false);
            lblGost.setVisible(true);
            cbGost.setVisible(true);
            lblRecepcioner.setVisible(true);
            cbRecepcioner.setVisible(true);
            cbDrzava.setVisible(false);
            lblDrzava.setVisible(false);
        } else if (rbGost.isSelected()) {
            lblNacin.setText("Ime:");
            lblNacinRez.setText("Broj:");
            lblDrzava.setText("Drzava:");
            lblDatum.setText("Prezime:");
            lblUkupanIznos.setText("Email:");
            lblRecepcioner.setVisible(false);
            cbRecepcioner.setVisible(false);
            lblExtra.setVisible(false);
            txtExtra.setVisible(false);
            lblBalkon.setVisible(false);
            checkboxBalkon.setVisible(false);
            lblGost.setVisible(false);
            cbGost.setVisible(false);
            cbDrzava.setVisible(true);
            lblDrzava.setVisible(true);
        } else if (rbRecepcioner.isSelected()) {
            lblNacin.setText("Ime:");
            lblNacinRez.setText("Broj:");
            lblDatum.setText("Prezime:");
            lblUkupanIznos.setText("Email:");
            lblExtra.setText("Korisnicko ime:");
            lblGost.setVisible(false);
            cbGost.setVisible(false);
            lblRecepcioner.setVisible(false);
            cbRecepcioner.setVisible(false);
            lblBalkon.setVisible(false);
            checkboxBalkon.setVisible(false);
            lblExtra.setVisible(true);
            txtExtra.setVisible(true);
            cbDrzava.setVisible(false);
            lblDrzava.setVisible(false);
        } else {
            lblNacin.setText("Broj:");
            lblNacinRez.setText("Sprat:");
            lblDatum.setText("Broj kreveta:");
            lblUkupanIznos.setText("Cena po danu(RSD):");
            lblBalkon.setText("Balkon:");
            lblGost.setVisible(false);
            cbGost.setVisible(false);
            lblRecepcioner.setVisible(false);
            cbRecepcioner.setVisible(false);
            lblExtra.setVisible(false);
            txtExtra.setVisible(false);
            lblBalkon.setVisible(true);
            checkboxBalkon.setVisible(true);
            cbDrzava.setVisible(false);
            lblDrzava.setVisible(false);
        }
        this.pack();
    }

    private void fillCbDrzava() throws Exception {
        cbDrzava.removeAllItems();
        List<Drzava> drzave = Controller.getInstance().vratiListuSvihDrzava();
        for (Drzava drzava : drzave) {
            cbDrzava.addItem(drzava);
        }
        cbDrzava.setSelectedIndex(-1);
    }
}
