/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import domain.StrucnaSprema;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import table.models.TableModelStrucnaSprema;
import validation.ValidationException;
import validation.Validator;

/**
 *
 * @author Nikola
 */
public class StrucnaSpremaForm extends javax.swing.JDialog {

    TableModelStrucnaSprema tableModelStrucnaSprema;
    
    
    /**
     * Creates new form StrucnaSpremaForm
     */
    public StrucnaSpremaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setTitle("Strucne spreme");
        initComponents();
        fillTable();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaziv = new javax.swing.JLabel();
        lblStepen = new javax.swing.JLabel();
        lblInstitucija = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        txtStepen = new javax.swing.JTextField();
        txtInstitucija = new javax.swing.JTextField();
        btnZapamti = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStrucnaSprema = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNaziv.setText("Naziv:");

        lblStepen.setText("Stepen:");

        lblInstitucija.setText("Institucija:");

        btnZapamti.setText("Zapamti");
        btnZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapamtiActionPerformed(evt);
            }
        });

        tblStrucnaSprema.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStrucnaSprema);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnZapamti))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStepen)
                            .addComponent(lblNaziv)
                            .addComponent(lblInstitucija))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(txtStepen)
                            .addComponent(txtInstitucija))))
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaziv)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStepen)
                    .addComponent(txtStepen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstitucija)
                    .addComponent(txtInstitucija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnZapamti)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapamtiActionPerformed
        try {
            validateStrucnaSprema();
            StrucnaSprema s = new StrucnaSprema();
            s = Controller.getInstance().ubaciStrucnaSprema(s);
            s.setNaziv(txtNaziv.getText().trim());
            s.setStepen(txtStepen.getText().trim());
            s.setInstitucija(txtInstitucija.getText().trim());
            Controller.getInstance().promeniStrucnaSprema(s);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio strucnu spremu", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
            tableModelStrucnaSprema.addStrucnaSprema(s);
        } catch (ValidationException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska pri unosu podataka", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti strucnu spremu", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnZapamtiActionPerformed

    private void validateStrucnaSprema() throws ValidationException {
        Validator.startValidation()
                .validateNotNullOrEmpty(txtNaziv.getText(), "Morate uneti naziv!")
                .validateNotNullOrEmpty(txtStepen.getText(), "Morate uneti stepen!")
                .validateStringLength(txtStepen.getText(), "Stepen mora imati manje od 7 karaktera!", null, 6)
                .validateNotNullOrEmpty(txtInstitucija.getText(), "Morate uneti instituciju!")
                .throwIfInvalid();
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnZapamti;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInstitucija;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblStepen;
    private javax.swing.JTable tblStrucnaSprema;
    private javax.swing.JTextField txtInstitucija;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtStepen;
    // End of variables declaration//GEN-END:variables

    private void fillTable() {
        try {
            List<StrucnaSprema> strucneSpreme = Controller.getInstance().vratiListuSvihStrucnihSprema();
            tableModelStrucnaSprema = new TableModelStrucnaSprema(strucneSpreme);
            tblStrucnaSprema.setModel(tableModelStrucnaSprema);
            this.pack();
        } catch (Exception ex) {
            Logger.getLogger(StrucnaSpremaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
